language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src

install:
    - pip install -U platformio
    - platformio upgrade --dev  # for early Zephyr integration
    - platformio update

addons:
    apt:
        packages:
            - doxygen

script:
    - platformio run -e bms_5s50_sc -e bms_15s80_sc_bq76930 -e bms_8s50_ic
    - platformio test -e unit_test_isl94202 -e unit_test_bq769x0
    - doxygen Doxyfile

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: html
    github_token: $GH_REPO_TOKEN
    on:
        branch: master
