# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: libresolar
      revision: v3.2-branch
      import:
        name-whitelist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_stm32
          - tinycrypt
    - name: oled-display-library
      remote: libresolar
      revision: 523b26c103de56714fcda655702d600870a671bc
      path: modules/oled-display
    - name: thingset-zephyr-sdk
      remote: thingset
      revision: adb1accd280ef91668bd592233dde3e42195e9b9
      path: thingset-zephyr-sdk
      import:
        name-whitelist:
          - thingset-device-library
    - name: unity
      remote: throwtheswitch
      revision: 74cde089e65c3435ce9aa87d5c69f4f16b7f6ade
      path: modules/unity
