manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: libresolar
      revision: v2.5-branch
      # path must be something else than zephyr as we get a Kconfig include recursion otherwise
      path: rtos
      import:
        # main zephyr modules should be placed in here into zephyr subdirectory
        path-prefix: zephyr
        # only get modules we actually need
        name-whitelist:
          - cmsis
          - edtt
          - hal_stm32
    - name: thingset-device-library
      remote: thingset
      revision: 634f4e92854ce4f1b7c4c41f1d8f3b0af7801de4
      path: zephyr/modules/thingset
    - name: unity
      path: zephyr/modules/unity
      revision: 74cde089e65c3435ce9aa87d5c69f4f16b7f6ade
      remote: throwtheswitch
